feat/upgrade antfu eslint config v2
LouisHaftmann/configs pull request #14
Opened 2023-11-21 18:10 UTC by DrJume

- feat!: upgrade to @antfu/eslint-config v2 & use eslint flat config
- chore: release v2.0.0

2023-11-21 18:11 UTC, LouisHaftmann commented
dachte das is antfu eslint config v1? xd

2023-11-21 19:58 UTC, LouisHaftmann requested changes

2023-11-21 19:58 UTC, LouisHaftmann commented on .vscode/settings.json
> +  "eslint.experimental.useFlatConfig": true,
muss das auch in die readme?

2023-11-21 22:05 UTC, DrJume commented on .vscode/settings.json
> +  "eslint.experimental.useFlatConfig": true,
Jo

2023-11-22 21:40 UTC, DrJume commented
LGTM

2023-11-23 08:51 UTC, LouisHaftmann approved these changes

2023-11-23 08:51 UTC, merged

2023-11-23 11:04 UTC, DrJume commented
❤️